site_name: BWS Docs

nav:
  - Home: index.md
  - API: API.md
  - SQL: SQL.md
  - Modelling: Model.md


plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]

theme: readthedocs